### ISSUE TITLE
NAs produced by integer overflow

### ISSUE THREAD

**Issue by vondoRishi** [devSJR/PCRedux#1]
Hi ,

I am getting following error from function `performeR`

> Warning message:

> In (TP + FP) * (TP + FN) * (TN + FP) : NAs produced by integer overflow

This is because i have large number of observations.

I propose to overcome this issue by replacing the denominator of MCC with ` (sqrt(TP+FP)*sqrt(TP+FN)*sqrt(TN+FP)*sqrt(TN+FN))`

with regards
Rishi

**Comment by devSJR** [comment]
Thanks, made suggested changes
